### ISSUE TITLE
Getting emails about a variety of problems related to images that don't show up and won't delete...

### ISSUE THREAD

**Issue by bjornmeansbear** [cape-io/mica.ezle.io#10]
Will flesh this out more as more info is gathered.

**Comment by webmasterkai** [comment]
If they don't show up maybe they've been deleted ;-b

**Comment by alexjacque** [comment]
Roommate (Leah Cooper) is having issue with her images being broken, the screenshot of the admin interface I think is particularly notable as there's some broken images that show up, and she can click and delete them and they go away, but when she logs back in they're back. Her profile overlay only shows three images (guessing the three broken ones) and the five shown in the admin interface don't seem to being  showing up.

![ghost files](http://i.imgur.com/0VidZsZ.png)

On the front end side of things her images aren't showing up and likely it's just the broken link problem, but her error console turns up this, but I'm not sure if this is related, so just... FYI I guess.

![error console](http://i.imgur.com/pIOlePc.png)

**Comment by webmasterkai** [comment]
I'm looking into this. We've had some issues with filenames that contain a pound sign.

**Comment by webmasterkai** [comment]
The three images had a # sign in the filename. I'll work on rejecting these before they get uploaded.

**Comment by bjornmeansbear** [comment]
thanks. Can you also do the same for Eunjung Park, epark02
I think she has images with # signs in their titles too... and is having the same issues as described by Alex for leah cooper

**Comment by webmasterkai** [comment]
same problem with epark02. I removed the two files with # signs.

**Comment by bjornmeansbear** [comment]
thanks @webmasterkai

**Comment by bjornmeansbear** [comment]
I think @kai has fixed this. Some of the offending images are still showing up on the live site, but the problem on the backend seems fixed. Hopefully the cache will expire on imgix and all will go to normal...
