### ISSUE TITLE
user "abae" claims that she has uploaded text, images, etc. but that they don't appear on the site

### ISSUE THREAD

**Issue by bjornmeansbear** [cape-io/mica.ezle.io#12]
How can I check these things without having to ask you to do it?

http://www.micagradshow.com/students/abae/

She does at least now appear in the curatorial practice list:
http://www.micagradshow.com/?programId=curatorial-practice-mfa
which she claimed she wasn't before, so at least that is an improvement.

**Comment by webmasterkai** [comment]
I see two profile images. The one that is currently shown and https://mica2015.imgix.net/abae/IMG_5711.JPG

I do not see any statement text. I do see that a value may have been saved at one time. Right now it's just an empty string. ""

**Comment by bjornmeansbear** [comment]
I think her profile pic is correct, so that's good. 
Hmmm. I'll let her know that she try to upload some more content...

**Comment by bjornmeansbear** [comment]
She hasn't uploaded anything yet! that explains it!
